---
general:
  namespace: microservice-redis
  microserviceName: microservice-redis
  appPort: 9000
redis:
  master:
    password: "ZPsz4L&SGh&z_)yW9kt,T"
    configmap:
      name: redis-master-configmap
    deployment:
      type: redis-master
      name: redis-master-deployment
      scale: 1
      containerName: redis-master
      image: bitnami/redis:5.0.9
    persistentVolumeClaim:
      name: redis-master-pvc
    service:
      name: redis-master-service
      servicePort: 6376
      serviceTargetPort: 6376
    host: redis-master-service.microservice-redis.svc.cluster.local
    pvc:
      name: redis-master-pvc
      storage: 1Gi
  slave:
    password: "ZPsz4L&SGh&z_)yW9kt,T"
    configmap:
      name: redis-slave-configmap
    deployment:
      containerName: redis-slave
      image: bitnami/redis:5.0.9
    service:
      serviceTargetPort: 6379
microservice:
  secret:
    name: microservice-secret
  deployment:
    name: microservice-deployment
    containerName: microservice
    image: IMAGE
    type: microservice-redis-sidecar
  configmap:
    name: microservice-configmap
  service:
    name: microservice-service
    servicePort: 80
  autoscaler:
    name: autoscaler-microservice
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
privateDockerRegistry:
  dockerconfigjson: dockerconfigjsonBASE64ENC
...