apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.microservice.secret.name}}
type: Opaque
data:
  slave-password: {{ .Values.redis.slave.password | b64enc }}
  master-password: {{ .Values.redis.master.password | b64enc }}