---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.microservice.configmap.name}}
  namespace: {{.Values.general.namespace}}
data:
  app_port: "{{.Values.general.appPort}}"
  app_host: "{{.Values.general.appHost}}"
  log_severity: "{{.Values.general.log_severity}}"
  master_redis_connection_name: master
  master_redis_port: "{{.Values.redis.master.service.servicePort}}"
  master_redis_host: {{.Values.redis.master.host}}
  master_redis_db: "0"
  slave_redis_connection_name: slave
  slave_redis_port: "{{.Values.redis.slave.service.serviceTargetPort}}"
  slave_redis_host: "127.0.0.1"
  slave_redis_db: "0"
...