---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.microservice.service.name}}
  namespace: {{.Values.general.namespace}}
spec:
  selector:
    app: {{.Values.general.microserviceName}}
    type: {{.Values.microservice.deployment.type}}
  ports:
  - protocol: TCP
    port: {{.Values.microservice.service.servicePort}}
    targetPort: {{.Values.general.appPort}}
...