---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: microservice-allow-out-53
  namespace: {{.Values.general.namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{.Values.general.microserviceName}}
      type: {{.Values.microservice.deployment.type}}   
  policyTypes:
  - Egress
  egress:
  - to:
    ports:
    - protocol: UDP
      port: 53

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: microservice-allow-out-6376
  namespace: {{.Values.general.namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{.Values.general.microserviceName}}
      type: {{.Values.microservice.deployment.type}}   
  policyTypes:
  - Egress
  egress:
  - to:
    ports:
    - protocol: TCP
      port: {{.Values.redis.master.service.servicePort}}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-master-allow-in-6376
  namespace: {{.Values.general.namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{.Values.general.microserviceName}}
      type: {{.Values.redis.master.deployment.type}}  
  policyTypes:
  - Ingress
  egress:
  - to:
    ports:
    - protocol: TCP
      port: {{.Values.redis.master.service.servicePort}}
...