---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.redis.master.service.name}}
  namespace: {{.Values.general.namespace}}
spec:
  selector:
    app: {{.Values.general.microserviceName}}
    type: {{.Values.redis.master.deployment.type}}
  ports:
  - protocol: TCP
    port: {{.Values.redis.master.service.servicePort}}
    targetPort: {{.Values.redis.master.service.serviceTargetPort}}
...